import categorical_methods_abstract_harmonic_analysis_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace categorical_methods_abstract_harmonic_analysis_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end categorical_methods_abstract_harmonic_analysis_lemma_canonical_lane_mathlib
end HautevilleHouse
